# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  basic:

services:
    #the service container names should all be different i think but copying jawads naming convention.
  ca.org1.medrex.com:
    image: hyperledger/fabric-ca
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca.org1.medrex.com
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    # /etc/hyperledger/fabric-ca-server-config is actually a virtual path. look to volumes 
    - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.medrex.com-cert.pem #ca.org1.example.com-cert.pem ????
    - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f384724d8053a3ff708043aed4431e9a4b0953b322f565a66b14cb11adb236db_sk
    - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    #copied from jawad's wout -cfg allowremove at the end
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.vehiclereg1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f384724d8053a3ff708043aed4431e9a4b0953b322f565a66b14cb11adb236db_sk -b admin:adminpw -d'
    volumes: #this sort -of renames the oldpath:newpath-to-be-used-in-environment-tag-upar
      - ./crypto-config/peerOrganizations/org1.medrex.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.medrex.com #ca.example.com
    networks:
    - basic

#should be ca1 
  ca.org2.medrex.com:
    image: hyperledger/fabric-ca
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca.org2.medrex.com
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.medrex.com-cert.pem
    - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/44510b993c7553bc84abfe4a4efa3864aac730e8cbccb11fd97568aca12a16d0_sk
    - FABRIC_CA_SERVER_PORT=8054
    ports:
    - "8054:8054"
    #copied from jawad's wout -cfg.identities.allowremove at the end
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.medrex.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/44510b993c7553bc84abfe4a4efa3864aac730e8cbccb11fd97568aca12a16d0_sk -b admin:adminpw -d'
    volumes:
    - ./crypto-config/peerOrganizations/org2.medrex.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org2.medrex.com
    networks:
    - basic
