# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.medrex.com:
  peer0.org1.medrex.com:
  peer1.org1.medrex.com:
  peer0.org2.medrex.com:
  peer1.org2.medrex.com:

networks:
  basic:

services:

  orderer.medrex.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.medrex.com
    container_name: orderer.medrex.com
    networks:
      - basic

  peer0.org1.medrex.com:
    container_name: peer0.org1.medrex.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.medrex.com
    #depends_on:
#     - orderer.medrex.com
#     - couchdb
    networks:
      - basic

  peer1.org1.medrex.com:
    container_name: peer1.org1.medrex.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.medrex.com
    networks:
      - basic

  peer0.org2.medrex.com:
    container_name: peer0.org2.medrex.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.medrex.com
    networks:
      - basic

  peer1.org2.medrex.com:
    container_name: peer1.org2.medrex.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.medrex.com
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.6
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.medrex.com:7051
      - CORE_PEER_TLS_ENABLED=true


    # use the following 4 lines in the cmd whenever you want to use peer 0 org 1. change for each peer accordingly.
    # reference https://hyperledger-fabric.readthedocs.io/en/release-1.4/build_network.html#create-join-channel
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.medrex.com/peers/peer0.org1.medrex.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.medrex.com/peers/peer0.org1.medrex.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.medrex.com/peers/peer0.org1.medrex.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.medrex.com/users/Admin@org1.medrex.com/msp

      
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.medrex.com
      - peer0.org1.medrex.com
      - peer1.org1.medrex.com
      - peer0.org2.medrex.com
      - peer1.org2.medrex.com
    networks:
      - basic
