
#### this is an extra uselss file ignore it

# orderer.medrex.com:
#     container_name: orderer.medrex.com
#     image: hyperledger/fabric-orderer
#     environment:
#     - ORDERER_GENERAL_LOGLEVEL=debug
#     - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
#     - ORDERER_GENERAL_GENESISMETHOD=file
#     - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
#     - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
#     - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
#     working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
#     command: orderer
#     ports:
#     - 7050:7050
#     volumes:
#     - ./config/:/etc/hyperledger/configtx
#     - ./crypto-config/ordererOrganizations/medrex.com/orderers/orderer.medrex.com/:/etc/hyperledger/msp/orderer
#     - ./crypto-config/peerOrganizations/org1.medrex.com/peers/peer0.org1.medrex.com/:/etc/hyperledger/msp/peerOrg1
#     networks:
#     - basic

#   peer0.org1.medrex.com:
#     container_name: peer0.org1.medrex.com
#     image: hyperledger/fabric-peer
#     environment:
#     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#     - CORE_PEER_ID=peer0.org1.medrex.com
#     - CORE_LOGGING_PEER=debug
#     - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
#     - CORE_PEER_LOCALMSPID=Org1MSP
#     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
#     - CORE_PEER_ADDRESS=peer0.org1.medrex.com:7051
#     # # the following setting starts chaincode containers on the same
#     # # bridge network as the peers
#     # # https://docs.docker.com/compose/networking/
#     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
#     - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
#     - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
#     # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
#     # provide the credentials for ledger to connect to CouchDB.  The username and password must
#     # match the username and password set for the associated CouchDB.
#     - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
#     - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
#     working_dir: /opt/gopath/src/github.com/hyperledger/fabric
#     command: peer node start
#     # command: peer node start --peer-chaincodedev=true
#     ports:
#     - 7051:7051
#     - 7053:7053
#     volumes:
#     - /var/run/:/host/var/run/
#     - ./crypto-config/peerOrganizations/org1.medrex.com/peers/peer0.org1.medrex.com/msp:/etc/hyperledger/msp/peer
#     - ./crypto-config/peerOrganizations/org1.medrex.com/users:/etc/hyperledger/msp/users
#     - ./config:/etc/hyperledger/configtx
#     depends_on:
#     - orderer.medrex.com
#     - couchdb
#     networks:
#     - basic

#   peer1.org1.medrex.com:
#         container_name: peer1.org1.medrex.com
#         extends:
#             file:  base/docker-compose-base.yaml
#             service: peer1.org1.medrex.com
#         networks:
#             - basic

#   peer0.org2.medrex.com:
#     container_name: peer0.org2.medrex.com
#     extends:
#         file:  base/docker-compose-base.yaml
#         service: peer0.org2.medrex.com
#     networks:
#         - basic

#   peer1.org2.medrex.com:
#     container_name: peer1.org2.medrex.com
#     extends:
#         file:  base/docker-compose-base.yaml
#         service: peer1.org2.medrex.com
#     networks:
#         - basic

#   couchdb:
#     container_name: couchdb
#     image: hyperledger/fabric-couchdb
#     # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
#     # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
#     environment:
#     - COUCHDB_USER=
#     - COUCHDB_PASSWORD=
#     ports:
#     - 5984:5984
#     networks:
#     - basic

#   cli:
#     container_name: cli
#     image: hyperledger/fabric-tools
#     tty: true
#     environment:
#     - GOPATH=/opt/gopath
#     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#     - CORE_LOGGING_LEVEL=DEBUG
#     - CORE_PEER_ID=cli

#     # use the following 4 lines in the cmd whenever you want to use peer 0 org 1. change for each peer accordingly.
#     # reference https://hyperledger-fabric.readthedocs.io/en/release-1.4/build_network.html#create-join-channel
#     - CORE_PEER_ADDRESS=peer0.org1.medrex.com:7051
#     - CORE_PEER_LOCALMSPID=Org1MSP
#     - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
#     - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt

#     - CORE_CHAINCODE_KEEPALIVE=10
#     working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
#     command: /bin/bash
#     volumes:
#     - /var/run/:/host/var/run/
#     - ./../chaincode/:/opt/gopath/src/github.com/phr
#     - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
#     depends_on:
#         - orderer.medrex.com
#         - peer0.org1.medrex.com
#         - peer1.org1.medrex.com
#         - peer0.org2.medrex.com
#         - peer1.org2.medrex.com
#     networks:
#     - basic